name: home_brigadier_admin_panel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_storage: 2.1.1
  image_picker:
  flutter_svg: 2.0.10+1
  intl:
  syncfusion_flutter_calendar: ^25.2.3
  fluttertoast: 8.2.5
  flutter_echarts: ^2.5.0
  syncfusion_flutter_charts: ^25.2.3+1
  marquee: ^2.2.3
  dio: 5.4.3+1
  connectivity_plus: 6.0.3
  google_fonts: 6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_launcher_icons: 0.13.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/launcher/
  uses-material-design: true

